### ISSUE TITLE
Displaying challenge questions?

### ISSUE THREAD

**Issue by noamross** [datacarpentry/2015-02-09-ucdavis#2]
@tracykteal What's your preferred approach to giving the challenge questions to the students?  Both Michael and I were planning to print out the lessons for ourselves to have as we live-code, but it would make sense to put the questions in the lessons up for students to see, no?  I guess we could just drop them in the etherpad when we ask them, or paste them in the "editor" window in RStudio?  We'll only have one screen.

**Comment by tracykteal** [comment]
It definitely is good to put the exercises up. Since the students won't need to see the coding while they're working on their own, I generally put the exercise up on the screen while they're working on it.

I like making the Exercises their own Markdown file or set of slides to put up. If we had the Exercises set before the workshop, alternatively or in addition we could print them out. The library does conveniently have printing and photocopying capabilities.

Maybe this is overly complicated, but something I've done in the past is to use sed to extract the Exercises from the README and put them in a separate markdown file. I did this in a separate lesson 

https://github.com/tracykteal/shell-genomics/tree/gh-pages

with formatting the Exercise sections in a particular way in the README and extraction with

sed -n '/***/,/***/ p' < README.md | sed '/***/ d' > Exercises.md

We could even slidify the Markdown and have each exercise be its own slide. I did that for the intro slides in that repo too to make these slides. 
http://tracykteal.github.io/shell-genomics/slides.html

That would have to be in the gh-pages branch though and again maybe too hacky.

**Comment by noamross** [comment]
I can extract the R Challenge questions to slides and put them on the gh-pages branch, so we can just have a browser to flip to from the RStudio console.  I'll aim to do this Sunday afternoon in case anyone wants to make changes to the questions beforehand.

**Comment by noamross** [comment]
Challenge for the questions for the R lessons are at:
-   http://datacarpentry.github.io/2015-02-09-ucdavis/r-challenge-questions-day-1.html
-   http://datacarpentry.github.io/2015-02-09-ucdavis/r-challenge-questions-day-2.html

Note that some still require code to be dropped into the etherpad by one of the instructors.

@tracykteal: The shell challenge questions didn't lend themselves well to slides.  There tended to be a lot of questions together at the end of each lesson, so it was too much text to put on a slide.  I could break them up, so each question at the end of each lesson is a slide, or I could print them out.
